### ISSUE TITLE
Questions on screenshot

### ISSUE THREAD

**Issue by imoby** [nichabosh/minimal#1]
Can I ask what file icon theme you're using there?

**Comment by nichabosh** [comment]
Of course! I'm using @cdonohue's [Quill Icons](https://marketplace.visualstudio.com/items?itemName=cdonohue.quill-icons#review-details) extension. You can also check out my [`settings.json`](https://github.com/nichabosh/minimal/blob/master/settings.json) for other configurations seen in the screenshot.
